spring:
  application:
    name: APIS2025BACK

  data:
    mongodb:
      uri: 'mongodb+srv://dev:CU5JaXKB5ScZ2ogQ@apis-tpo-cluster.ca1h1z1.mongodb.net/ecommerce'

  security:
    user:
      name: 'user'
      password: 'password'
