spring:
  application:
    name: APIS2025BACK

  data:
    mongodb:
      uri: 'mongodb+srv://dev:GiM9c11oSScFQMAp@apis-tpo-cluster.ca1h1z1.mongodb.net/ecommerce'

  security:
    user:
      name: ${SC_USERNAME}
      password: ${SC_PASSWORD}
