spring:
  application:
    name: APIS2025BACK

  data:
    mongodb:
      uri: ${DB_URI}
      auto-index-creation: true

  security:
    user:
      name: 'dev'
      password: 'mmMannLPfWhj49Mx'

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      persistAuthorization: true
    api-docs:
      path: /v3/api-docs
