spring:
  application:
    name: APIS2025BACK

  data:
    mongodb:
      uri: 'mongodb+srv://dev:6BPJLXM0Me7miIxZ@apis-tpocluster.ca1h1z1.mongodb.net/ecommerce'

  security:
    user:
      name: 'dev'
      password: '6BPJLXM0Me7miIxZ'
