spring:
  application:
    name: APIS2025BACK

  data:
    mongodb:
      uri: '${DB_URI}'
      auto-index-creation: true

  security:
    user:
      name: ${SC_USERNAME}
      password: ${SC_PASSWORD}

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      persistAuthorization: true
    api-docs:
      path: /v3/api-docs
